version: '3.8'

services:
  django:
    build: ./
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8008:8008
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-pass
      - POSTGRES_DB=django_db

volumes:
  postgres_data: